//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;!--This document is intended only for use by authorized licensees of The Weather Channel. Unauthorized use is prohibited. Copyright 1995-2005, The Weather Channel Interactive, Inc. All Rights Reserved.--&gt;
        ///&lt;weather ver=&quot;2.0&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;locale&gt;en_US&lt;/locale&gt;
        ///    &lt;form&gt;MEDIUM&lt;/form&gt;
        ///    &lt;ut&gt;C&lt;/ut&gt;
        ///    &lt;ud&gt;km&lt;/ud&gt;
        ///    &lt;us&gt;km/h&lt;/us&gt;
        ///    &lt;up&gt;mb&lt;/up&gt;
        ///    &lt;ur&gt;mm&lt;/ur&gt;
        ///  &lt;/head&gt;
        ///  &lt;loc id=&quot;USGA0028&quot;&gt;
        ///    &lt;dnam&gt;Atlanta, GA&lt;/dnam&gt;
        ///    &lt;tm&gt;8:27 PM&lt;/tm&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeatherXml {
            get {
                return ResourceManager.GetString("WeatherXml", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_0 {
            get {
                object obj = ResourceManager.GetObject("wicon32_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_1 {
            get {
                object obj = ResourceManager.GetObject("wicon32_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_10 {
            get {
                object obj = ResourceManager.GetObject("wicon32_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_11 {
            get {
                object obj = ResourceManager.GetObject("wicon32_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_12 {
            get {
                object obj = ResourceManager.GetObject("wicon32_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_13 {
            get {
                object obj = ResourceManager.GetObject("wicon32_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_14 {
            get {
                object obj = ResourceManager.GetObject("wicon32_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_15 {
            get {
                object obj = ResourceManager.GetObject("wicon32_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_16 {
            get {
                object obj = ResourceManager.GetObject("wicon32_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_17 {
            get {
                object obj = ResourceManager.GetObject("wicon32_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_18 {
            get {
                object obj = ResourceManager.GetObject("wicon32_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_19 {
            get {
                object obj = ResourceManager.GetObject("wicon32_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_2 {
            get {
                object obj = ResourceManager.GetObject("wicon32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_20 {
            get {
                object obj = ResourceManager.GetObject("wicon32_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_21 {
            get {
                object obj = ResourceManager.GetObject("wicon32_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_22 {
            get {
                object obj = ResourceManager.GetObject("wicon32_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_23 {
            get {
                object obj = ResourceManager.GetObject("wicon32_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_24 {
            get {
                object obj = ResourceManager.GetObject("wicon32_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_25 {
            get {
                object obj = ResourceManager.GetObject("wicon32_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_26 {
            get {
                object obj = ResourceManager.GetObject("wicon32_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_27 {
            get {
                object obj = ResourceManager.GetObject("wicon32_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_28 {
            get {
                object obj = ResourceManager.GetObject("wicon32_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_29 {
            get {
                object obj = ResourceManager.GetObject("wicon32_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_3 {
            get {
                object obj = ResourceManager.GetObject("wicon32_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_30 {
            get {
                object obj = ResourceManager.GetObject("wicon32_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_31 {
            get {
                object obj = ResourceManager.GetObject("wicon32_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_32 {
            get {
                object obj = ResourceManager.GetObject("wicon32_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_33 {
            get {
                object obj = ResourceManager.GetObject("wicon32_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_34 {
            get {
                object obj = ResourceManager.GetObject("wicon32_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_35 {
            get {
                object obj = ResourceManager.GetObject("wicon32_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_36 {
            get {
                object obj = ResourceManager.GetObject("wicon32_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_37 {
            get {
                object obj = ResourceManager.GetObject("wicon32_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_38 {
            get {
                object obj = ResourceManager.GetObject("wicon32_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_39 {
            get {
                object obj = ResourceManager.GetObject("wicon32_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_4 {
            get {
                object obj = ResourceManager.GetObject("wicon32_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_40 {
            get {
                object obj = ResourceManager.GetObject("wicon32_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_41 {
            get {
                object obj = ResourceManager.GetObject("wicon32_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_42 {
            get {
                object obj = ResourceManager.GetObject("wicon32_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_43 {
            get {
                object obj = ResourceManager.GetObject("wicon32_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_44 {
            get {
                object obj = ResourceManager.GetObject("wicon32_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_45 {
            get {
                object obj = ResourceManager.GetObject("wicon32_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_46 {
            get {
                object obj = ResourceManager.GetObject("wicon32_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_47 {
            get {
                object obj = ResourceManager.GetObject("wicon32_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_5 {
            get {
                object obj = ResourceManager.GetObject("wicon32_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_6 {
            get {
                object obj = ResourceManager.GetObject("wicon32_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_7 {
            get {
                object obj = ResourceManager.GetObject("wicon32_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_8 {
            get {
                object obj = ResourceManager.GetObject("wicon32_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_9 {
            get {
                object obj = ResourceManager.GetObject("wicon32_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon32_na {
            get {
                object obj = ResourceManager.GetObject("wicon32_na", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_0 {
            get {
                object obj = ResourceManager.GetObject("wicon64_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_1 {
            get {
                object obj = ResourceManager.GetObject("wicon64_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_10 {
            get {
                object obj = ResourceManager.GetObject("wicon64_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_11 {
            get {
                object obj = ResourceManager.GetObject("wicon64_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_12 {
            get {
                object obj = ResourceManager.GetObject("wicon64_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_13 {
            get {
                object obj = ResourceManager.GetObject("wicon64_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_14 {
            get {
                object obj = ResourceManager.GetObject("wicon64_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_15 {
            get {
                object obj = ResourceManager.GetObject("wicon64_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_16 {
            get {
                object obj = ResourceManager.GetObject("wicon64_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_17 {
            get {
                object obj = ResourceManager.GetObject("wicon64_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_18 {
            get {
                object obj = ResourceManager.GetObject("wicon64_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_19 {
            get {
                object obj = ResourceManager.GetObject("wicon64_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_2 {
            get {
                object obj = ResourceManager.GetObject("wicon64_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_20 {
            get {
                object obj = ResourceManager.GetObject("wicon64_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_21 {
            get {
                object obj = ResourceManager.GetObject("wicon64_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_22 {
            get {
                object obj = ResourceManager.GetObject("wicon64_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_23 {
            get {
                object obj = ResourceManager.GetObject("wicon64_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_24 {
            get {
                object obj = ResourceManager.GetObject("wicon64_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_25 {
            get {
                object obj = ResourceManager.GetObject("wicon64_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_26 {
            get {
                object obj = ResourceManager.GetObject("wicon64_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_27 {
            get {
                object obj = ResourceManager.GetObject("wicon64_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_28 {
            get {
                object obj = ResourceManager.GetObject("wicon64_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_29 {
            get {
                object obj = ResourceManager.GetObject("wicon64_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_3 {
            get {
                object obj = ResourceManager.GetObject("wicon64_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_30 {
            get {
                object obj = ResourceManager.GetObject("wicon64_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_31 {
            get {
                object obj = ResourceManager.GetObject("wicon64_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_32 {
            get {
                object obj = ResourceManager.GetObject("wicon64_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_33 {
            get {
                object obj = ResourceManager.GetObject("wicon64_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_34 {
            get {
                object obj = ResourceManager.GetObject("wicon64_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_35 {
            get {
                object obj = ResourceManager.GetObject("wicon64_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_36 {
            get {
                object obj = ResourceManager.GetObject("wicon64_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_37 {
            get {
                object obj = ResourceManager.GetObject("wicon64_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_38 {
            get {
                object obj = ResourceManager.GetObject("wicon64_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_39 {
            get {
                object obj = ResourceManager.GetObject("wicon64_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_4 {
            get {
                object obj = ResourceManager.GetObject("wicon64_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_40 {
            get {
                object obj = ResourceManager.GetObject("wicon64_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_41 {
            get {
                object obj = ResourceManager.GetObject("wicon64_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_42 {
            get {
                object obj = ResourceManager.GetObject("wicon64_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_43 {
            get {
                object obj = ResourceManager.GetObject("wicon64_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_44 {
            get {
                object obj = ResourceManager.GetObject("wicon64_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_45 {
            get {
                object obj = ResourceManager.GetObject("wicon64_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_46 {
            get {
                object obj = ResourceManager.GetObject("wicon64_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_47 {
            get {
                object obj = ResourceManager.GetObject("wicon64_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_5 {
            get {
                object obj = ResourceManager.GetObject("wicon64_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_6 {
            get {
                object obj = ResourceManager.GetObject("wicon64_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_7 {
            get {
                object obj = ResourceManager.GetObject("wicon64_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_8 {
            get {
                object obj = ResourceManager.GetObject("wicon64_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_9 {
            get {
                object obj = ResourceManager.GetObject("wicon64_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wicon64_na {
            get {
                object obj = ResourceManager.GetObject("wicon64_na", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
